/*
 * This source file was generated by the Gradle 'init' task
 */
package engtelecom.std;

import module java.base; // Java 25: importação de módulo

public class ClienteUdp {
    private static final int BUFFER_SIZE = 1024;

    public sealed interface Resultado permits Resultado.Sucesso, Resultado.Falha {
        record Sucesso(String resposta) implements Resultado {}
        record Falha(String motivo) implements Resultado {}
    }

    public static Resultado comunicar(String[] config, String mensagem) {
        byte[] bufferEnvio = mensagem.getBytes(StandardCharsets.UTF_8);
        byte[] bufferRecepcao = new byte[BUFFER_SIZE];

        try (var socket = new DatagramSocket()) {
            var enderecoServidor = InetAddress.getByName(config[0]);
            int portaServidor = Integer.parseInt(config[1]);

            // Envio
            var pacoteEnvio = new DatagramPacket(bufferEnvio, bufferEnvio.length,       enderecoServidor, portaServidor);
            socket.send(pacoteEnvio);
            System.out.println("Mensagem enviada: " + mensagem);

            // Recepção
            System.out.println("Aguardando resposta...");
            var pacoteResposta = new DatagramPacket(bufferRecepcao, bufferRecepcao.length);
            socket.receive(pacoteResposta);

            String resposta = new String(
                pacoteResposta.getData(), 0, pacoteResposta.getLength(), StandardCharsets.UTF_8);

            return new Resultado.Sucesso(resposta);
        } catch (IOException e){
            return new Resultado.Falha(e.getMessage());
        }
    }

    public static void main(String[] args) {
        System.out.println("Cliente UDP iniciado...");

        var config = switch (args.length) {
            case 2 -> new String[]{ args[0], args[1] };
            default -> new String[]{ "localhost", "9876" };
        };

        switch (comunicar(config, "Olá, eu sou o cliente UDP!")) {
            case Resultado.Sucesso(var resposta) ->
                System.out.println("Resposta do servidor: " + resposta);
            case Resultado.Falha(var motivo) ->
                System.err.println("Falha na comunicação: " + motivo);
        }
    }
}
