/*
 * This source file was generated by the Gradle 'init' task
 */
package engtelecom.std;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.OutputStreamWriter;
import java.net.Socket;
import java.net.UnknownHostException;
import java.nio.charset.StandardCharsets;

public class App {
    public static void main(String[] args) {
        // String enderecoServidor = "127.0.0.1";
        // int portaServidor = 12345;
        String enderecoServidor = args[0];
        int portaServidor = Integer.parseInt(args[1]);
        
        try (
            Socket conexao = new Socket(enderecoServidor, portaServidor);
            var entrada = new BufferedReader(new InputStreamReader(conexao.getInputStream(), StandardCharsets.UTF_8));
            var saida = new BufferedWriter(new OutputStreamWriter(conexao.getOutputStream(), StandardCharsets.UTF_8));
        ){
            System.out.printf("Conectado em %s:%d%n \n", enderecoServidor, portaServidor);

            // aqui começa o protocolo
            //1- cliente envia   
            saida.write("Olá Servidor \n");
            saida.newLine();
            saida.flush();

            //2- servidor responde oi
            String respostaDoServidor = entrada.readLine();
            System.out.printf("Servidor disse: %s \n", respostaDoServidor);

        } catch(Exception e){
            System.err.println("erro " + e);
        }
    }
}

// package engtelecom.std;

// import java.io.BufferedReader;
// import java.io.BufferedWriter;
// import java.io.IOException;
// import java.io.InputStreamReader;
// import java.io.OutputStreamWriter;
// import java.net.Socket;
// import java.net.UnknownHostException;
// import java.nio.charset.StandardCharsets;

// public class App {
//     public static void main(String[] args) {
//         String enderecoServidor = "127.0.0.1";
//         int portaServidor = 12345;

        
//         try (
//             Socket conexao = new Socket(enderecoServidor, portaServidor);
//             var entrada = new BufferedReader(new InputStreamReader(conexao.getInputStream(), StandardCharsets.UTF_8));
//             var saida = new BufferedWriter(new OutputStreamWriter(conexao.getOutputStream(), StandardCharsets.UTF_8));
//         ){
//             System.out.printf("Conectado em %s:%d%n \n", enderecoServidor, portaServidor);

//             // aqui começa o protocolo
//             //1- cliente envia oi        
//             saida.write("Olá Servidor");
//             saida.newLine();
//             saida.flush();

//             String respostaDoServidor = "";

//             while (!respostaDoServidor.equals("fim")) {
//                 respostaDoServidor = entrada.readLine();
//                 System.out.printf("Servidor disse: %s \n", respostaDoServidor);
//             }          
            

//         } catch(Exception e){
//             System.err.println("erro " + e);
//         }
//     }
// }
