/*
 * This source file was generated by the Gradle 'init' task
 */
package engtelecom.std;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.InputStreamReader;
import java.io.OutputStreamWriter;
import java.net.ServerSocket;
import java.nio.charset.StandardCharsets;
import java.util.concurrent.Executors;

public class App {
    public static void main(String[] args) {
        int porta = (args.length > 0) ? Integer.parseInt(args[0]) : 12345;

        System.out.printf("Servidor ouvindo na porta: %d%n", porta);

        try (
            var conexao = new ServerSocket(porta);
            var executor = Executors.newVirtualThreadPerTaskExecutor()
        ){
            while(!Thread.currentThread().isInterrupted()){
                //espera cliente conectar
                var cliente = conexao.accept();
                //criar uma thread para atender esse cliente
                executor.submit(new AtenderCliente(cliente));
            }

        } catch (Exception e) {
            System.err.println("erro " + e);
        }
    }
}