/*
 * This source file was generated by the Gradle 'init' task
 */
package engtelecom.std;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.InputStreamReader;
import java.io.OutputStreamWriter;
import java.net.ServerSocket;
import java.net.Socket;
import java.nio.charset.StandardCharsets;
import java.util.concurrent.Executors;

public record AtenderCliente(Socket cliente) implements Runnable {
    @Override
    public void run() {
        try (
            cliente;

            var entrada = new BufferedReader(new InputStreamReader(cliente.getInputStream(), StandardCharsets.UTF_8));
            var saida = new BufferedWriter(new OutputStreamWriter(cliente.getOutputStream(), StandardCharsets.UTF_8));
        ){
            var endereco = cliente.getInetAddress().getHostAddress();
            var portaCliente = cliente.getPort();

            System.out.println("Cliente conectado em " + endereco + portaCliente);


            // aqui começa o protocolo
            //1- cliente escreve
            String mensagemDoCliente = entrada.readLine();
            System.out.printf("Cliente disse: %s%n \n", mensagemDoCliente);

            //2- servidor responde
            saida.write("Oi cliente, tudo bem?");
            saida.newLine();
            saida.flush();

        } catch (Exception e) {
            System.err.println("erro " + e);
        }
    }
}